# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(FFFFF9)
$foreground = rgb(0F181F)
$color0 = rgb(FFFFF9)
$color1 = rgb(5D6F6C)
$color2 = rgb(3B6E93)
$color3 = rgb(356C95)
$color4 = rgb(34688E)
$color5 = rgb(244258)
$color6 = rgb(192833)
$color7 = rgb(0F181F)
$color8 = rgb(82826E)
$color9 = rgb(7C9390)
$color10 = rgb(4E93C3)
$color11 = rgb(4790C6)
$color12 = rgb(458ABE)
$color13 = rgb(305875)
$color14 = rgb(223644)
$color15 = rgb(05080A)
