# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #0F181F
background         #FFFFF9
cursor             #2F5571

active_tab_foreground     #FFFFF9
active_tab_background     #0F181F
inactive_tab_foreground   #0F181F
inactive_tab_background   #FFFFF9

active_border_color   #0F181F
inactive_border_color #FFFFF9
bell_border_color     #5D6F6C

color0      #FFFFF9
color1		#5D6F6C
color2		#3B6E93
color3		#356C95
color4		#34688E
color5		#244258
color6		#192833
color7		#0F181F
color8		#82826E
color9		#7C9390
color10		#4E93C3
color11		#4790C6
color12		#458ABE
color13		#305875
color14		#223644
color15		#05080A
