# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #33281F
background         #FAFFFF
cursor             #615A51

active_tab_foreground     #FAFFFF
active_tab_background     #33281F
inactive_tab_foreground   #33281F
inactive_tab_background   #FAFFFF

active_border_color   #33281F
inactive_border_color #FAFFFF
bell_border_color     #775639

color0      #FAFFFF
color1		#775639
color2		#6C6963
color3		#49697C
color4		#456980
color5		#456980
color6		#554334
color7		#33281F
color8		#6E8281
color9		#9F734D
color10		#908C84
color11		#628CA6
color12		#5C8CAA
color13		#5C8CAA
color14		#715945
color15		#110D0A
